config/routes.rb
Rails.application.routes.draw do
  root 'home#top' # トップページ
  
  get 'top'           => 'home#top'           # トップページ
  get 'service'       => 'home#service'       # 事業内容ページ
  get 'portfolio'     => 'home#portfolio'     # 施工事例
  get 'contact'       => 'home#contact'       # お問い合わせページ
  get 'company'       => 'home#company'       # 会社案内ページ
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
    @images = [ "top1.jpg", "top2.jpg", "top3.jpg" ]
    @menus = [
      { content: "事業内容", link: "/service", image: "reform2.jpg" },
      { content: "施工事例", link: "/portfolio", image: "reform3.jpg" },
      { content: "お問い合わせ",link: "/contact", image: "reform4.jpg" },
      { content: "案内", link: "/company", image: "reform1.jpg" }
    ]
  end

  def company
    @company = {
      # "会社" => "株式会社おうちの110番",
      "所在地" => "東京都葛飾区西水元5-16-1",
      "代表取締役" => "松原 翔梧",
      "TEL" => "070-1148-3961",
      "事業内容" => "住宅リフォーム"
    }

    @makers = { lixil: "lixil.png", toto: "toto.png", tostem: "tostem.png", sankyo: "sankyo.png", sunwave: "sunwave.png", panaspnic: "panasonic.png", mitsubishi: "mitsubishi.png", sangetsu: "sangetsu.png", noda: "noda.png", lilikara: "lilikara.png", kurinap: "kurinap.png", kmew: "kmew.png" }
  end

  def service
    @houses = { 
      "屋根" => "葺き替え防水処理などが可能。構造によってトップライト（天窓）や吹抜けも作れます。",
      "外壁" => "塗装、張り替えなどが可能。張り替えの場合は地域によっては防火規制を確認した方が良い。",
      "玄関ドア" => "交換可能。地域によっては防火規制を確認した方が良い。",
      "屋内クラス" => "張り替え可能。構造によっては耐震補強や断熱材施工ができるので考えている場合は一緒に行う方が良い。",
      "床下" => "基礎の補強や床下断熱、フローリングの張り替えなどが可能。",
      "水回り" => "移動や増設などは比較的自由にできます。",
      "間取り" => "基本的に自由度の高いリフォームが可能ですが、構造上取り除くことができない壁や柱もありますので、弊社専門スタッフにご相談ください。",
      "増築" => "建築基準法に沿ってリフォームすることが可能です。また地域によってそれぞれ規制等もありますので、弊社専門スタッフにご相談ください。"
    }

    @mansion = {
      "天井" => "天井板を外して構造体の内側までなら天井の高さをあげることも可能です。",
      "窓・サッシの交換" => "窓やサッシはベランダ・バルコニーと同じく共用部に該当しますので自由な取り換え等はできません。窓ガラスの交換、内窓の取り付けは可能です。",
      "玄関ドア" => "玄関ドアも共用部にあたります。そのため、ドア自体の交換はできません。ドアの内側のみを塗り替えたりクロス張りすることは可能です。",
      "室内" => "壁や天井のクロスの張替え、塗装等が可能です。また、室内ドアの交換も可能です。",
      "床" => "管理規約に沿った材料であればフローリングの張り替えなどが可能です。床暖房を取り付ける場合は各住戸で使えるエネルギーの使用可能量を事前に調べておく必要があります。",
      "水回り" => "排水管などが通るパイプスペースは共用部で移設ができないため、パイプスペースの位置と構造によって制限がでてきます。キッチンやバス、便器などの交換は可能です。",
      "間取り" => "マンションの構造によっては外せない壁があり、その場合間取りに制限が発生します。"
    }
  end

  def portfolio
   
    @cases = {
      "case_btn01.jpg" => "case01: キッチン工事",
      "case_btn02.jpg" => "case02: 手すり取り付け工事",
      "case_btn03.jpg" => "case03: 瓦屋根葺き替え工事",
      "case_btn04.jpg" => "case04: フルリフォーム工事",
      "case_btn05.jpg" => "case05: トイレの交換",
      "case_btn06.jpg" => "case06: リビング工事",
      "case_btn07.jpg" => "case07: 基礎補強工事",
      "case_btn08.jpg" => "case08: トイレ戸棚工事",
      "case_btn09.jpg" => "case09: 畳張り替え工事",
      "case_btn10.jpg" => "case10: 和室のリフォーム",
      "case_btn11.jpg" => "case11: エアコン組み込み工事",
      "case_btn12.jpg" => "case12: セメント瓦から横暖ルーフへの葺き替え工事",
      "case_btn13.jpg" => "case13: ユニットバス交換工事",
      "case_btn14.jpg" => "case14: 劣化した塗装面工事",
      "case_btn15.jpg" => "case15: 換気扇交換工事",
      "case_btn16.jpg" => "case16: 雨樋点検修理",
      "case_btn17.jpg" => "case17: 地震で壊れた土壁工事",
      "case_btn18.jpg" => "case18: 玄関ドアの交換",
      "case_btn19.jpg" => "case19: ハウスクリーニング",
      "case_btn20.jpg" =>"case20: シャワー取り替え工事"
    }
  end

  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/company/home.html.erb
<h1>トップページ</h1>

app/views/home/_footer.html.erb
<footer>
  <div class="footer-top">
    <p>住宅リフォーム おうちの110番</p>
    <p>東京都葛飾区西水元5-16-1</p>
  </div>
  <div class="footer-bottom">
    <p>Copyright © おうちの110番 All Rights Reserved.</p>
  </div>
</footer>

app/views/home/_header.html.erb
<header>
  <div class="header-left">
    <%= link_to root_path, class: "header-left-heading" do %>
      住宅リフォーム おうちの110番
    <% end %>
  </div>
  <%= fa_icon 'bars', class: 'menu-icon', id: 'bars' %>
  <div class="header-right">
    <%= link_to '事業内容', service_path %>
    <%= link_to '施工事例', portfolio_path %>
    <%= link_to 'お問い合わせ', contact_path %>
    <%= link_to '　案内　', company_path %>
  </div>
</header>

app/views/home/company.html.erb
<div class="company">
  <div class="company-content">
    <div class="company-menu">
      <span class="menu-list">
        <a class="menu-title active">会社概要</a>
      </span>
      <span class="menu-list">
        <a class="menu-title">使用メーカー 一覧</a>
      </span>
    </div>
    <%# 会社概要 %>
    <div class="content-info" id="company">
      <ul class="info-list">
        <% @company.each do |head,content| %>
          <li class="list-content">
            <span class="table-head">
              <%= head %>
            </span>
            <span class="table-content">
              <%= content %>
            </span>
          </li>
        <% end %>
      </ul>
    </div>
    <%# 使用メーカー %>
    <div class="content-info" id="maker">
      <ul class="maker-list">
        <% @makers.each do |name, img| %>
          <li class="maker-content">
            <%= image_tag img, alt: name %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/home/contact.html.erb
<div class="contact">
  <%= image_tag "contact.jpg", alt: "お問い合わせ" %>
  <div class="contact-heading">
    <h1 class="heading-top">お問い合わせ</h1>
    <h1 class="heading-bottom">家のリフォームなんでも承ります<h1>
  </div>
</div>
<div class="content">
  <h1 class="content-top light-blue">CONTACT</h1>
  <p class="content-text">お問い合わせ</p>
  <h1 class="content-bottom light-blue">
    外装・内装・リフォームの見積りなど<br>
    まずはお気軽にご相談ください
  </h1>
  <p class="content-text">
    家のリフォームやトラブルで、困っていることがございましたら、一度ご連絡ください！<br>
    お電話でのご相談やメールでのご相談、ご要望に応じて対応させていただきます
  </p>
  <div class="tel">
    <p class="tel-heading light-blue">お急ぎの方はお電話ください</p>
    <%= link_to '070-1148-3961', 'tel:070-1148-3961' %>
    <%= link_to 'メールでお問い合わせする', 'mailto:outino110tokyo@gmail.com?subject=リフォームお問い合わせ&amp;body=ご相談内容をご入力ください' %>
  </div>
</div>

app/views/home/portfolio.html.erb
<div class="portfolio">
  <div class="portfolio-content">
    <div class="case-message">
      <p class="pctab">おうちの110番の高い技術により、たくさんのお客様にご満足して頂いております</p>
      <p class="pctab">その中で一部ではありますが、施工事例をご紹介させて頂きます</p>
      <p class="smart">施工事例一覧</p>
    </div>
    <div class="case-list">
      <% @cases.each do |image,title| %>
        <ul class="list">
          <li class="case-content">
            <%= image_tag image %>
          </li>
          <li class="case-title">
            <%= title %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/home/possible.html.erb
<div class="wrap">
  <%= render 'header'%>
  <div class="main">
    <div class="bgwrap">
      <div class="renovalead">
        <p>
          建設時には必要な確認申請を受けると言う公的機関のチェックもリフォームの場合はほとんど必要としません。その代わり構造の違いや、
          <br>
            建築基準法・地域の条例などの法的な規約によってできることが変わってきますし、戸建とマンションによってもその制限は変わってきます。
          </br>
        </p>
        <p>ここでは一般的なできること・できないことを説明致します。</p>
        <p>やりたいリフォームによっては家の構造・法的規制などが変わってくる場合もありますので、お気軽にお問い合わせください。</p>
      </div>
      <div class="tabMenu">
        <span class="tab01 active">
          <%= fa_icon 'arrow-right'%>
          <a href="/company">
            戸田て
          </a>
        </span>
        <span class="tab02">
          <%= fa_icon 'arrow-right'%>
          <a href="#">
            マンション
          </a>
        </span>
      </div>

      <div class="tabContents01">
        <p class="renovationImage">
          <img src="" alt="">
        </p>
        <div class="renovationInner">
          <p>
            戸建のリフォームは建物、敷地を含めてご自身の持ち物なので、様々なリフォームが比較的自由に可能です。
          </p>
          <p>
            しかし、リフォームの内容によっては建物の構造や、建築基準法・地域条例等の制約を受ける場合もあります。
          </p>
        </div>
        <ul class="tableBox">
          <li>
            <span class="tblhead">屋根</span>
            <span class="tblcont">葺き替え防水処理などが可能。構造によってトップライト（天窓）や吹抜けも作れます。</span>
          </li>
          <li>
            <span class="tblhead">外壁</span>
            <span class="tblcont">塗装、張り替えなどが可能。張り替えの場合は地域によっては防火規制を確認した方が良い。</span>
          </li>
          <li>
            <span class="tblhead">玄関ドア</span>
            <span class="tblcont">交換可能。地域によっては防火規制を確認した方が良い。</span>
          </li>
          <li>
            <span class="tblhead">屋内クラス</span>
            <span class="tblcont">張り替え可能。構造によっては耐震補強や断熱材施工ができるので考えている場合は一緒に行う方が良い。</span>
          </li>
          <li>
            <span class="tblhead">床下</span>
            <span class="tblcont">基礎の補強や床下断熱、フローリングの張り替えなどが可能。</span>
          </li>
          <li>
            <span class="tblhead">水回り</span>
            <span class="tblcont">移動や増設などは比較的自由にできます。</span>
          </li>
          <li>
            <span class="tblhead">間取り</span>
            <span class="tblcont">基本的に自由度の高いリフォームが可能ですが、構造上取り除くことができない壁や柱もありますので、弊社専門スタッフにご相談ください。</span>
          </li>
          <li>
            <span class="tblhead">増築</span>
            <span class="tblcont">建築基準法に沿ってリフォームすることが可能です。また地域によってそれぞれ規制等もありますので、弊社専門スタッフにご相談ください。</span>
          </li>
        </ul>
      </div>

    </div>

    <div class="topicpath">
      <p>
        <a href="/top">
          <%= fa_icon 'home'%>
        </a>
        <%= fa_icon 'angle-right'%>
        会社案内
      </p>
    </div>

    <div class="menus">
      <div class="menu">
        <ul>
          <li>
            <a href="/company">
              <img class="img-1" src="/assets/reform4.jpg" alt="会社案内">
              <p>会社案内</p>
            </a>
          </li>
  
          <li>
            <a href="/possible">
              <img class="img-2" src="/assets/reform2.jpg" alt="事業内容">
              <p>事業内容</p>
            </a>
          </li>
  
          <li>
            <a href="#">
              <img class="img-3" src="/assets/reform5.jpg" alt="施工事例">
              <p>施工事例</p>
            </a>
          </li>
  
          <li>
            <a href="#">
              <img class="img-4" src="/assets/reform3.jpg" alt="お問い合わせ">
              <p>お問い合わせ</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <%= render 'footer'%>
</div>

app/views/home/service.html.erb
<div class="service">
  <div class="service-content">
    <div class="service-menu">
      <span class="menu-list">
        <a class="menu-title active">戸建て</a>
      </span>
      <span class="menu-list">
        <a class="menu-title">マンション</a>
      </span>
    </div>
    <!-- 戸建て -->
    <div class="content-info" id="house">
      <ul class="info-list">
        <% @houses.each do |head,content| %>
          <li class="list-content">
            <span class="table-head">
              <%= head %>
            </span>
            <span class="table-content">
              <%= content %>
            </span>
          </li>
        <% end %>
      </ul>
    </div>
    <!-- マンション -->
    <div class="content-info" id="mansion">
      <ul class="info-list">
        <% @mansion.each do |head,content| %>
          <li class="list-content">
            <span class="table-head">
              <%= head %>
            </span>
            <span class="table-content">
              <%= content %>
            </span>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/home/top.html.erb
<div class="slider">
  <% @images.each do |image| %>
    <div class="slick-content">
      <%= image_tag "#{image}", alt: "リフォームイメージ" %>
    </div>
  <% end %>
</div>
<div class="top-content">
  <h1 class="top-content-top">理想の住まいと生活を実現します</h1>
  <h1 class="top-content-bottom">家のお悩みをなんでも解決します</h1>
</div>
<div class="menu-wrapper">
  <ul class="flex-list">
    <% @menus.each_with_index do |item,i| %>
      <li class="list<%= i + 1 %>">
        <%= link_to item[:link] do %>
          <%= image_tag item[:image], alt: item[:content] %>
          <p><%= item[:content] %></p>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>住宅リフォーム おうちの110番</title>
    <meta name="description" content="住宅リフォーム専門、おうちの110番のWebサイトです。リフォームのことでお困りのことがあれば、なんでも相談致します。内装・外装・キッチン・トイレ・お風呂・外壁・屋根・ハウスクリーニングなど、なんでも対応致します。">
    <meta name="keyword" content="リフォーム,住宅リフォーム,東京リフォーム,千葉リフォーム,神奈川リフォーム,内装,外装,キッチン,トイレ,風呂,外壁,屋根">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <%= render 'header' %>
    <%= yield %>
    <%= render 'footer' %>
  </body>
</html>